[package]
name = "xkcd2rss"
version = "0.1.0"
authors = ["Benjamin Bouvier <public@benj.me>"]

[dependencies]
reqwest = "0.8.5"
select = "0.4.2"
rss = "1.5.0"
regex = "1.0.1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_yaml = "0.7.5"
